name: 'jaffle_shop'

config-version: 2
version: '0.1'

profile: 'jaffle_shop'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  jaffle_shop:
      +materialized: view
      staging:
        database: "{{ 'STAGING_DEV' if target.name == 'dev' else 'STAGING' }}"
      canon:
        database: "{{ 'CANON_DEV' if target.name == 'dev' else 'CANON' }}"
      marts:
        database: "{{ 'MARTS_DEV' if target.name == 'dev' else 'MARTS' }}"
        +materialized: table
      
        
